apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: sbuasa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: sengsathit/brief-api:latest
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: database_host
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: database_port
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user-password
            - name: MYSQL_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: database_name
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "800m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "3Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
