apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sbuasa-ingress
  namespace: sbuasa
  annotations:
    # Réécriture du chemin pour l'API
    nginx.ingress.kubernetes.io/rewrite-target: /$1

    # Pour éviter les erreurs de redirection Streamlit
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  ingressClassName: nginx
  rules:
    - host: 172.189.159.252.nip.io
      http:
        paths:
          # API Back end
          - path: /sbuasa
            pathType: ImplementationSpecific
            backend:
              service:
                name: api
                port:
                  number: 5000
          - path: /sbuasa/health
            pathType: ImplementationSpecific
            backend:
              service:
                name: api
                port:
                  number: 5000
          - path: /sbuasa/clients
            pathType: ImplementationSpecific
            backend:
              service:
                name: api
                port:
                  number: 5000
          - path: /sbuasa/clients/
            pathType: ImplementationSpecific
            backend:
              service:
                name: api
                port:
                  number: 5000
          # Front Streamlit
          - path: /sbuasa-streamlit
            pathType: ImplementationSpecific
            backend:
              service:
                name: streamlit
                port:
                  number: 8501
