apiVersion: v1
kind: ConfigMap
metadata:
  name: front-config
  namespace: sbuasa
data:
  # Le front appelle l’API via le service interne du cluster
  API_URL: "http://api-service.sbuasa.svc.cluster.local:8000"
