apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: sbuasa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: blackphoenix2020/streamlit-front:1.0.0
          ports:
            - containerPort: 8501
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
