apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: sbuasa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: blackphoenix2020/streamlit-front:1.0.0
          env:
          - name: API_URL
            value: "http://api.svc.cluster.local:5000"
          ports:
            - containerPort: 8501
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "600m"
              memory: "768Mi"
