name: CI-CD AKS

on:
  push:
    branches:
      - feature/k8s
      - main

jobs:
  deploy-to-aks:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}   # service principal JSON

      - name: Bootstrap AKS infra (RG, AKS, namespace, ingress)
        run: bash ./scripts/aks-bootstrap.sh
      
      - name: kubectl apply manifests
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/backend/configmap.yaml -n sbuasa
          kubectl apply -f k8s/backend/secret.yaml -n sbuasa
          kubectl apply -f k8s/backend/pvc.yaml -n sbuasa
          kubectl apply -f k8s/backend/db-deployment.yaml -n sbuasa
          kubectl apply -f k8s/backend/db-service.yaml -n sbuasa
          kubectl apply -f k8s/backend/api-deployment.yaml -n sbuasa
          kubectl apply -f k8s/backend/api-service.yaml -n sbuasa
          kubectl apply -f k8s/front/front-deployment.yaml -n sbuasa
          kubectl apply -f k8s/front/front-service.yaml -n sbuasa
          kubectl apply -f k8s/network/ingress.yaml -n sbuasa
