name: CI-CD AKS

on:
  push:
    branches:
      - feature/k8s
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push front image
        uses: docker/build-push-action@v4
        with:
          context: ./front
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/streamlit-front:latest

  deploy-to-aks:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}   # service principal JSON

      - name: Set AKS context
        run: |
          az aks get-credentials --resource-group RG_AKS_SBUASA --name cluster-sbuasa --admin
      - name: kubectl apply manifests
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/backend/configmap.yaml -n sbuasa
          kubectl apply -f k8s/backend/secret.yaml -n sbuasa
          kubectl apply -f k8s/backend/pvc.yaml -n sbuasa
          kubectl apply -f k8s/backend/db-deployment.yaml -n sbuasa
          kubectl apply -f k8s/backend/db-service.yaml -n sbuasa
          kubectl apply -f k8s/backend/api-deployment.yaml -n sbuasa
          kubectl apply -f k8s/backend/api-service.yaml -n sbuasa
          kubectl apply -f k8s/front/front-deployment.yaml -n sbuasa
          kubectl apply -f k8s/front/front-service.yaml -n sbuasa
          kubectl apply -f k8s/network/ingress.yaml -n sbuasa
