name: Full Pipeline

on:
  push:
    branches: [ feature/k8s_api-mysql, main ]
  workflow_dispatch:

permissions:
  contents: write   # ✅ autorise mkdocs gh-deploy
  pages: write
  id-token: write
  packages: write

jobs:
  deploy-docs:
    uses: ./.github/workflows/mkdocs-deploy.yaml

  deploy-aks:
    uses: ./.github/workflows/ci-cd.yaml
