name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

    paths:
      - mkdocs_aks_library/**

  workflow_dispatch:
  workflow_call:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs
        run: |
          pip install mkdocs mkdocs-material pymdown-extensions

      - name: Deploy documentation
        working-directory: mkdocs_aks_library
        run: |
          mkdocs gh-deploy --force
